server:
  port: 10086

spring:
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    static-path-pattern: /statics/**
    throw-exception-if-no-handler-found: true

--- #################### mybatisPlus相关配置 ####################
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰和下划线对应
    map-underscore-to-camel-case: true

--- #################### 接口文档相关配置 ####################
knife4j:
  enable: true
  openapi:
    title: 凉茶后台接口文档
    description: "**根据yudao源码进行修改(学习用)**"
    email: G2494552478@hotmail.com
    concat: 凉茶
    url: /
    version: v1.0
    license: Apache 2.0
    license-url: /
    terms-of-service-url: /

--- #################### 自定义相关配置 ####################
liangcha:
  captcha:
    #验证码开关
    enable: false
    expire-times: 3m

  security:
    # 请求头名称
    token-header: Authorization
    # 加密复杂度
    password-encoder-length: 4
    # token过期时间
    token-expire-times: 30m
    # refreshToken过期时间
    refresh-token-expire-times: 3d
    # token前缀
    authorization-bearer: Bearer
    # 允许不登陆访问的路径
    permit-all-urls:
      # 接口
      - /auth/login
      - /captcha/get
      - /sms/send-sms-code
      - /auth/refresh-token
      # swagger需要不登录访问的路径
      - /doc.html
      - /favicon.ico
      - /swagger-resources
      - /v2/api-docs
      # 其余
      - /websocket/message

  sms-code: # 短信验证码相关的配置项
    expire-times: 10m
    send-frequency: 1m
    send-maximum-quantity-per-day: 10
    begin-code: 9999 # 这里配置 9999 的原因是，测试方便。
    end-code: 9999 # 这里配置 9999 的原因是，测试方便。
