spring:
  redis:
    host: 127.0.0.1
    port: 6379


  datasource: #数据库基本配置
    dynamic: #使用@DS切换数据源
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://124.223.63.101:3306/ruoyi-vue-pro?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
          username: root
          password: woshidashuaibi
          type: com.alibaba.druid.pool.DruidDataSource
        slave:
          url: jdbc:mysql://124.223.63.101:3306/ruoyi-vue-pro?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
          username: root
          password: woshidashuaibi
          type: com.alibaba.druid.pool.DruidDataSource

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
