server:
  port: 10086

spring:
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    static-path-pattern: /statics/**
    throw-exception-if-no-handler-found: true

--- #################### mybatisPlus相关配置 ####################
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰和下划线对应
    map-underscore-to-camel-case: true

--- #################### 验证码相关配置 ####################
aj:
  captcha:
    jigsaw: classpath:images/jigsaw # 滑动验证，底图路径，不配置将使用默认图片；以 classpath: 开头，取 resource 目录下路径
    pic-click: classpath:images/pic-click # 滑动验证，底图路径，不配置将使用默认图片；以 classpath: 开头，取 resource 目录下路径
    cache-type: redis # 缓存 local/redis...
    cache-number: 1000 # local 缓存的阈值,达到这个值，清除缓存
    timing-clear: 0 # local定时清除过期缓存(单位秒),设置为0代表不执行
    type: clickWord # 验证码类型 default两种都实例化。 blockPuzzle 滑块拼图 clickWord 文字点选
    water-mark: \u51c9\u8336 # 右下角水印文字(我的水印)，可使用 https://tool.chinaz.com/tools/unicode.aspx 中文转 Unicode，Linux 可能需要转 unicode
    interference-options: 0 # 滑动干扰项(0/1/2)
    req-frequency-limit-enable: false # 接口请求次数一分钟限制是否开启 true|false
    req-get-lock-limit: 5 # 验证失败 5 次，get接口锁定
    req-get-lock-seconds: 10 # 验证失败后，锁定时间间隔
    req-get-minute-limit: 30 # get 接口一分钟内请求数限制
    req-check-minute-limit: 60 # check 接口一分钟内请求数限制
    req-verify-minute-limit: 60 # verify 接口一分钟内请求数限制

--- #################### 自定义相关配置 ####################
liangcha:
  security:
    authorizationBearer: Bearer
    permit-all_urls:
      - /auth/login
      - /captcha/get
      - /captcha/check
      - /websocket/message
      #swagger需要不登录访问的路径
      - /doc.html
      - /favicon.ico
      - /swagger-resources
      - /v2/api-docs

--- #################### 接口文档相关配置 ####################
knife4j:
  enable: true
  openapi:
    title: 凉茶后台接口文档
    description: "**根据yudao源码进行修改(学习用)**"
    email: G2494552478@hotmail.com
    concat: 凉茶
    url: /
    version: v1.0
    license: Apache 2.0
    license-url: /
    terms-of-service-url: /
