server:
  port: 10086

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB #限制单个文件上传大小为10M
      max-request-size: 200MB #限制总上传文件大小

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    static-path-pattern: /statics/**
    throw-exception-if-no-handler-found: true

--- #################### mybatisPlus相关配置 ####################
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰和下划线对应
    map-underscore-to-camel-case: true

--- #################### 接口文档相关配置 ####################
knife4j:
  enable: true
  openapi:
    title: liangcha-yudao后台接口文档
    description: "**根据yudao源码进行修改(学习用)**"
    email: G2494552478@hotmail.com
    concat: 凉茶
    url: /
    version: v1.0
    license: Apache 2.0
    license-url: /
    terms-of-service-url: /

--- #################### 自定义相关配置 ####################
liangcha:
  captcha:
    #验证码开关
    enable: false
    expire-times: 3m

  security:
    token-header: Authorization # 请求头名称
    password-encoder-length: 4 # 加密复杂度
    token-expire-times: 3d # token过期时间
    refresh-token-expire-times: 3d # refreshToken过期时间
    client-expire-times: 10d # client过期时间
    auth2-code-expire-times: 4m # oauth2授权码过期时间
    approve-expire-times: 30d # 授权信息过期时间
    authorization-bearer: Bearer # token前缀
    permit-all-urls: # 允许不登陆访问的路径
      # 接口
      - /test
      - /captcha/get
      - /sms/send-sms-code
      - /system/auth/login
      - /system/auth/refresh-token
      - /system/oauth2/check-token
      - /system/oauth2/token
      - /system/file/download/**
      # swagger需要不登录访问的路径
      - /doc.html
      - /favicon.ico
      - /swagger-resources
      - /v2/api-docs
      # websocket
      - /websocket/message
      # 其它
      - /error

  sms-code: # 短信验证码相关的配置项
    expire-times: 10m
    send-frequency: 1m
    send-maximum-quantity-per-day: 10
    begin-code: 9999 # 这里配置 9999 的原因是，测试方便。
    end-code: 9999 # 这里配置 9999 的原因是，测试方便。
