spring:
  datasource: #数据库基本配置
    dynamic: #使用@DS切换数据源
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://124.223.63.101:3306/ruoyi-vue-pro?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
          username: root
          password: woshidashuaibi
          type: com.alibaba.druid.pool.DruidDataSource
        slave:
          url: jdbc:mysql://124.223.63.101:3306/ruoyi-vue-pro?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
          username: root
          password: woshidashuaibi
          type: com.alibaba.druid.pool.DruidDataSource

liangcha:
  security: #安全框架配置
    authorizationBearer: Bearer
    permit-all_urls:
      - /auth/login
      - /captcha/get
      - /captcha/check
      - /websocket/message
      #swagger需要不登录访问的路径
      - /doc.html
      - /favicon.ico
      - /swagger-resources
      - /v2/api-docs

#接口文档配置
knife4j:
  enable: true
  openapi:
    title: 凉茶后台接口文档
    description: "**根据yudao源码进行修改(学习用)**"
    email: G2494552478@hotmail.com
    concat: 凉茶
    url: /
    version: v1.0
    license: Apache 2.0
    license-url: /
    terms-of-service-url: /

#阿里缓存操作框架
jetcache:
  areaInCacheName: false #设置不把areaName作为Key前缀
  local: # 本地缓存
    default:
      type: linkedhashmap
      keyConvertor: fastjson  # 使用json工具技术

  remote: # 远程缓存

    default: # 默认
      type: redis
      port: 6379
      host: 124.223.63.101
      valueEncoder: java
      valueDecoder: java
      keyConvertor: fastjson
      poolConfig:
        maxTotal: 50 #最大连接数
