server:
  port: 10086

spring:
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    static-path-pattern: /statics/**
    throw-exception-if-no-handler-found: true

--- #################### mybatisPlus相关配置 ####################
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰和下划线对应
    map-underscore-to-camel-case: true

--- #################### 自定义相关配置 ####################
liangcha:
  captcha: true #验证码开关
  security:
    authorizationBearer: Bearer
    permit-all_urls:
      - /auth/login
      - /captcha/get
      - /captcha/check
      - /websocket/message
      #swagger需要不登录访问的路径
      - /doc.html
      - /favicon.ico
      - /swagger-resources
      - /v2/api-docs

--- #################### 接口文档相关配置 ####################
knife4j:
  enable: true
  openapi:
    title: 凉茶后台接口文档
    description: "**根据yudao源码进行修改(学习用)**"
    email: G2494552478@hotmail.com
    concat: 凉茶
    url: /
    version: v1.0
    license: Apache 2.0
    license-url: /
    terms-of-service-url: /
