spring:
  redis:
    host: 127.0.0.1
    port: 6379

  rabbitmq:
    host: localhost  # rabbitmq的ip地址
    port: 5672      # 端口
    username:
    password:
    virtual-host: / # 虚拟主机
    listener:
      direct:
        prefetch: 1  # 每次只能获取一条消息，处理完成才能获取下一个消息,不让消息堆积给消费者(让消费者按照能力消费)

  datasource: # 数据库基本配置
    dynamic: # 使用@DS切换数据源
      primary: master # 设置默认的数据源或者数据源组,默认值即为master
      strict: false # 严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/liangcha-yudao?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
          username: root
          password: root
          type: com.alibaba.druid.pool.DruidDataSource
        slave:
          url: jdbc:mysql://localhost:3306/liangcha-yudao?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
          username: root
          password: root
          type: com.alibaba.druid.pool.DruidDataSource

# minio配置
minio:
  url: localhost:9000  # 对象存储服务的URL
  accessKey: root # Access key账户
  secretKey: root # Secret key密码

sms:
  tencent:
    accessKeyId:  #腾讯云的accessKey
    accessKeySecret:  #腾讯云的accessKeySecret
    signature:  #短信签名
    sdkAppId:  #短信sdkAppId
    connTimeout: 60 #请求超时时间 默认60秒

jetcache:
  statIntervalMinutes: 30
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
